openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Database Migration Service Endpoints #X Amz Target=AmazonDMSv20160101.DescribeRecommendations API'
  description: <fullname>Database Migration Service</fullname> <p>Database Migration Service (DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to PostgreSQL.</p> <p>For more information about DMS, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html">What Is Database Migration Service?</a> in the <i>Database Migration Service User Guide.</i> </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: dms
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/dms-2016-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: https://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: http://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
- url: https://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AmazonDMSv20160101.DescribeRecommendations'
paths:
  /#X-Amz-Target=AmazonDMSv20160101.DescribeRecommendations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeRecommendations
      description: Returns a paginated list of target engine recommendations for your source databases.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeRecommendationsResponse'
        '480':
          description: InvalidResourceStateFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResourceStateFault'
        '481':
          description: AccessDeniedFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedFault'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeRecommendationsRequest'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AmazonDMSv20160101.DescribeRecommendations
      tags:
      - '#X Amz Target=AmazonDMSv20160101.DescribeRecommendations'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    RdsRecommendation:
      type: object
      properties:
        RequirementsToTarget:
          allOf:
          - $ref: '#/components/schemas/RdsRequirements'
          - description: Supplemental information about the requirements to the recommended target database on Amazon RDS.
        TargetConfiguration:
          allOf:
          - $ref: '#/components/schemas/RdsConfiguration'
          - description: Supplemental information about the configuration of the recommended target database on Amazon RDS.
      description: Provides information that describes a recommendation of a target engine on Amazon RDS.
    Filter:
      type: object
      required:
      - Name
      - Values
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the filter as specified for a <code>Describe*</code> or similar operation.
        Values:
          allOf:
          - $ref: '#/components/schemas/FilterValueList'
          - description: The filter value, which can specify one or more values used to narrow the returned results.
      description: 'Identifies the name and value of a filter object. This filter is used to limit the number and type of DMS objects that are returned for a particular <code>Describe*</code> call or similar operation. Filters are used as an optional parameter for certain API operations. '
    DescribeRecommendationsRequest:
      type: object
      title: DescribeRecommendationsRequest
      properties:
        Filters:
          allOf:
          - $ref: '#/components/schemas/FilterList'
          - description: Filters applied to the target engine recommendations described in the form of key-value pairs.
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: The maximum number of records to include in the response. If more records exist than the specified <code>MaxRecords</code> value, Fleet Advisor includes a pagination token in the response so that you can retrieve the remaining results.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>Specifies the unique pagination token that makes it possible to display the next page of results. If this parameter is specified, the response includes only records beyond the marker, up to the value specified by <code>MaxRecords</code>.</p> <p>If <code>NextToken</code> is returned by a previous response, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Make the call again using the returned token to retrieve the next page. Keep all other arguments unchanged.</p>
    BooleanOptional:
      type: boolean
    FilterValueList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    DescribeRecommendationsResponse:
      type: object
      properties:
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique pagination token returned for you to pass to a subsequent request. Fleet Advisor returns this token when the number of records in the response is greater than the <code>MaxRecords</code> value. To retrieve the next page, make the call again using the returned token and keeping all other arguments unchanged.
        Recommendations:
          allOf:
          - $ref: '#/components/schemas/RecommendationList'
          - description: The list of recommendations of target engines that Fleet Advisor created for the source database.
    RdsConfiguration:
      type: object
      properties:
        EngineEdition:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Describes the recommended target Amazon RDS engine edition.
        InstanceType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Describes the recommended target Amazon RDS instance type.
        InstanceVcpu:
          allOf:
          - $ref: '#/components/schemas/DoubleOptional'
          - description: Describes the number of virtual CPUs (vCPU) on the recommended Amazon RDS DB instance that meets your requirements.
        InstanceMemory:
          allOf:
          - $ref: '#/components/schemas/DoubleOptional'
          - description: Describes the memory on the recommended Amazon RDS DB instance that meets your requirements.
        StorageType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>Describes the storage type of the recommended Amazon RDS DB instance that meets your requirements.</p> <p>Amazon RDS provides three storage types: General Purpose SSD (also known as gp2 and gp3), Provisioned IOPS SSD (also known as io1), and magnetic (also known as standard).</p>'
        StorageSize:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: Describes the storage size of the recommended Amazon RDS DB instance that meets your requirements.
        StorageIops:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: Describes the number of I/O operations completed each second (IOPS) on the recommended Amazon RDS DB instance that meets your requirements.
        DeploymentOption:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Describes the deployment option for the recommended Amazon RDS DB instance. The deployment options include Multi-AZ and Single-AZ deployments. Valid values include <code>"MULTI_AZ"</code> and <code>"SINGLE_AZ"</code>.
      description: Provides information that describes the configuration of the recommended target engine on Amazon RDS.
    DoubleOptional:
      type: number
      format: double
    RecommendationSettings:
      type: object
      required:
      - InstanceSizingType
      - WorkloadType
      properties:
        InstanceSizingType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The size of your target instance. Fleet Advisor calculates this value based on your data collection type, such as total capacity and resource utilization. Valid values include <code>"total-capacity"</code> and <code>"utilization"</code>.
        WorkloadType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The deployment option for your target engine. For production databases, Fleet Advisor chooses Multi-AZ deployment. For development or test databases, Fleet Advisor chooses Single-AZ deployment. Valid values include <code>"development"</code> and <code>"production"</code>.
      description: Provides information about the required target engine settings.
    InvalidResourceStateFault: {}
    Recommendation:
      type: object
      properties:
        DatabaseId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identifier of the source database for which Fleet Advisor provided this recommendation.
        EngineName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the target engine. Valid values include <code>"rds-aurora-mysql"</code>, <code>"rds-aurora-postgresql"</code>, <code>"rds-mysql"</code>, <code>"rds-oracle"</code>, <code>"rds-sql-server"</code>, and <code>"rds-postgresql"</code>.
        CreatedDate:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The date when Fleet Advisor created the target engine recommendation.
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the target engine recommendation. Valid values include <code>"alternate"</code>, <code>"in-progress"</code>, <code>"not-viable"</code>, and <code>"recommended"</code>.
        Preferred:
          allOf:
          - $ref: '#/components/schemas/BooleanOptional'
          - description: Indicates that this target is the rightsized migration destination.
        Settings:
          allOf:
          - $ref: '#/components/schemas/RecommendationSettings'
          - description: The settings in JSON format for the preferred target engine parameters. These parameters include capacity, resource utilization, and the usage type (production, development, or testing).
        Data:
          allOf:
          - $ref: '#/components/schemas/RecommendationData'
          - description: The recommendation of a target engine for the specified source database.
      description: <p>Provides information that describes a recommendation of a target engine.</p> <p>A <i>recommendation</i> is a set of possible Amazon Web Services target engines that you can choose to migrate your source on-premises database. In this set, Fleet Advisor suggests a single target engine as the right sized migration destination. To determine this rightsized migration destination, Fleet Advisor uses the inventory metadata and metrics from data collector. You can use recommendations before the start of migration to save costs and reduce risks.</p> <p>With recommendations, you can explore different target options and compare metrics, so you can make an informed decision when you choose the migration target.</p>
    RecommendationData:
      type: object
      properties:
        RdsEngine:
          allOf:
          - $ref: '#/components/schemas/RdsRecommendation'
          - description: The recommendation of a target Amazon RDS database engine.
      description: Provides information about the target engine for the specified source database.
    AccessDeniedFault: {}
    IntegerOptional:
      type: integer
    String:
      type: string
    RdsRequirements:
      type: object
      properties:
        EngineEdition:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The required target Amazon RDS engine edition.
        InstanceVcpu:
          allOf:
          - $ref: '#/components/schemas/DoubleOptional'
          - description: The required number of virtual CPUs (vCPU) on the Amazon RDS DB instance.
        InstanceMemory:
          allOf:
          - $ref: '#/components/schemas/DoubleOptional'
          - description: The required memory on the Amazon RDS DB instance.
        StorageSize:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: The required Amazon RDS DB instance storage size.
        StorageIops:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: The required number of I/O operations completed each second (IOPS) on your Amazon RDS DB instance.
        DeploymentOption:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The required deployment option for the Amazon RDS DB instance. Valid values include <code>"MULTI_AZ"</code> for Multi-AZ deployments and <code>"SINGLE_AZ"</code> for Single-AZ deployments.
      description: Provides information that describes the requirements to the target engine on Amazon RDS.
    RecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/Recommendation'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/dms/
x-hasEquivalentPaths: true
