openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Database Migration Service Endpoints #X Amz Target=AmazonDMSv20160101.DescribeTableStatistics API'
  description: <fullname>Database Migration Service</fullname> <p>Database Migration Service (DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to PostgreSQL.</p> <p>For more information about DMS, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html">What Is Database Migration Service?</a> in the <i>Database Migration Service User Guide.</i> </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: dms
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/dms-2016-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: https://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: http://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
- url: https://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AmazonDMSv20160101.DescribeTableStatistics'
paths:
  /#X-Amz-Target=AmazonDMSv20160101.DescribeTableStatistics:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeTableStatistics
      description: <p>Returns table statistics on the database migration task, including table name, rows inserted, rows updated, and rows deleted.</p> <p>Note that the "last updated" column the DMS console only indicates the time that DMS last updated the table statistics record for a table. It does not indicate the time of the last update to the table.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeTableStatisticsResponse'
        '480':
          description: ResourceNotFoundFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundFault'
        '481':
          description: InvalidResourceStateFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResourceStateFault'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeTableStatisticsMessage'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AmazonDMSv20160101.DescribeTableStatistics
      tags:
      - '#X Amz Target=AmazonDMSv20160101.DescribeTableStatistics'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    Filter:
      type: object
      required:
      - Name
      - Values
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the filter as specified for a <code>Describe*</code> or similar operation.
        Values:
          allOf:
          - $ref: '#/components/schemas/FilterValueList'
          - description: The filter value, which can specify one or more values used to narrow the returned results.
      description: 'Identifies the name and value of a filter object. This filter is used to limit the number and type of DMS objects that are returned for a particular <code>Describe*</code> call or similar operation. Filters are used as an optional parameter for certain API operations. '
    BooleanOptional:
      type: boolean
    FilterValueList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    TableStatisticsList:
      type: array
      items:
        $ref: '#/components/schemas/TableStatistics'
    TStamp:
      type: string
      format: date-time
    InvalidResourceStateFault: {}
    DescribeTableStatisticsResponse:
      type: object
      example:
        Marker: ''
        ReplicationTaskArn: ''
        TableStatistics: []
      properties:
        ReplicationTaskArn:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Resource Name (ARN) of the replication task.
        TableStatistics:
          allOf:
          - $ref: '#/components/schemas/TableStatisticsList'
          - description: The table statistics.
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' An optional pagination token provided by a previous request. If this parameter is specified, the response includes only records beyond the marker, up to the value specified by <code>MaxRecords</code>. '
      description: <p/>
    TableStatistics:
      type: object
      properties:
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The schema name.
        TableName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the table.
        Inserts:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of insert actions performed on a table.
        Deletes:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of delete actions performed on a table.
        Updates:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of update actions performed on a table.
        Ddls:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The data definition language (DDL) used to build and modify the structure of your tables.
        AppliedInserts:
          allOf:
          - $ref: '#/components/schemas/LongOptional'
          - description: The number of insert actions applied on a target table.
        AppliedDeletes:
          allOf:
          - $ref: '#/components/schemas/LongOptional'
          - description: The number of delete actions applied on a target table.
        AppliedUpdates:
          allOf:
          - $ref: '#/components/schemas/LongOptional'
          - description: The number of update actions applied on a target table.
        AppliedDdls:
          allOf:
          - $ref: '#/components/schemas/LongOptional'
          - description: The number of data definition language (DDL) statements used to build and modify the structure of your tables applied on the target.
        FullLoadRows:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of rows added during the full load operation.
        FullLoadCondtnlChkFailedRows:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of rows that failed conditional checks during the full load operation (valid only for migrations where DynamoDB is the target).
        FullLoadErrorRows:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of rows that failed to load during the full load operation (valid only for migrations where DynamoDB is the target).
        FullLoadStartTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time when the full load operation started.
        FullLoadEndTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time when the full load operation completed.
        FullLoadReloaded:
          allOf:
          - $ref: '#/components/schemas/BooleanOptional'
          - description: A value that indicates if the table was reloaded (<code>true</code>) or loaded as part of a new full load operation (<code>false</code>).
        LastUpdateTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The last time a table was updated.
        TableState:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The state of the tables described.</p> <p>Valid states: Table does not exist | Before load | Full load | Table completed | Table cancelled | Table error | Table is being reloaded</p>'
        ValidationPendingRecords:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of records that have yet to be validated.
        ValidationFailedRecords:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of records that failed validation.
        ValidationSuspendedRecords:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The number of records that couldn't be validated.
        ValidationState:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The validation state of the table.</p> <p>This parameter can have the following values:</p> <ul> <li> <p>Not enabled – Validation isn't enabled for the table in the migration task.</p> </li> <li> <p>Pending records – Some records in the table are waiting for validation.</p> </li> <li> <p>Mismatched records – Some records in the table don't match between the source and target.</p> </li> <li> <p>Suspended records – Some records in the table couldn't be validated.</p> </li> <li> <p>No primary key –The table couldn't be validated because it has no primary key.</p> </li> <li> <p>Table error – The table wasn't validated because it's in an error state and some data wasn't migrated.</p> </li> <li> <p>Validated – All rows in the table are validated. If the table is updated, the status can change from Validated.</p> </li> <li> <p>Error – The table couldn't be validated because of an unexpected error.</p> </li> <li> <p>Pending validation – The table is waiting validation.</p> </li> <li> <p>Preparing table – Preparing the table enabled in the migration task for validation.</p> </li> <li> <p>Pending revalidation – All rows in the table are pending validation after the table was updated.</p> </li> </ul>
        ValidationStateDetails:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Additional details about the state of validation.
      description: Provides a collection of table statistics in response to a request by the <code>DescribeTableStatistics</code> operation.
    IntegerOptional:
      type: integer
    String:
      type: string
    DescribeTableStatisticsMessage:
      type: object
      required:
      - ReplicationTaskArn
      title: DescribeTableStatisticsMessage
      properties:
        ReplicationTaskArn:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Resource Name (ARN) of the replication task.
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: '<p> The maximum number of records to include in the response. If more records exist than the specified <code>MaxRecords</code> value, a pagination token called a marker is included in the response so that the remaining results can be retrieved. </p> <p>Default: 100</p> <p>Constraints: Minimum 20, maximum 500.</p>'
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' An optional pagination token provided by a previous request. If this parameter is specified, the response includes only records beyond the marker, up to the value specified by <code>MaxRecords</code>. '
        Filters:
          allOf:
          - $ref: '#/components/schemas/FilterList'
          - description: '<p>Filters applied to table statistics.</p> <p>Valid filter names: schema-name | table-name | table-state</p> <p>A combination of filters creates an AND condition where each record matches all specified filters.</p>'
      description: <p/>
    Long:
      type: integer
    ResourceNotFoundFault: {}
    LongOptional:
      type: integer
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/dms/
x-hasEquivalentPaths: true
