openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Database Migration Service Endpoints #X Amz Target=AmazonDMSv20160101.ModifyEventSubscription API'
  description: <fullname>Database Migration Service</fullname> <p>Database Migration Service (DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to PostgreSQL.</p> <p>For more information about DMS, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html">What Is Database Migration Service?</a> in the <i>Database Migration Service User Guide.</i> </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: dms
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/dms-2016-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: https://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: http://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
- url: https://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AmazonDMSv20160101.ModifyEventSubscription'
paths:
  /#X-Amz-Target=AmazonDMSv20160101.ModifyEventSubscription:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ModifyEventSubscription
      description: 'Modifies an existing DMS event notification subscription. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyEventSubscriptionResponse'
        '480':
          description: ResourceQuotaExceededFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceQuotaExceededFault'
        '481':
          description: ResourceNotFoundFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundFault'
        '482':
          description: SNSInvalidTopicFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SNSInvalidTopicFault'
        '483':
          description: SNSNoAuthorizationFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SNSNoAuthorizationFault'
        '484':
          description: KMSAccessDeniedFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSAccessDeniedFault'
        '485':
          description: KMSDisabledFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSDisabledFault'
        '486':
          description: KMSInvalidStateFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSInvalidStateFault'
        '487':
          description: KMSNotFoundFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSNotFoundFault'
        '488':
          description: KMSThrottlingFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSThrottlingFault'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyEventSubscriptionMessage'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AmazonDMSv20160101.ModifyEventSubscription
      tags:
      - '#X Amz Target=AmazonDMSv20160101.ModifyEventSubscription'
components:
  schemas:
    EventSubscription:
      type: object
      properties:
        CustomerAwsId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services customer account associated with the DMS event notification subscription.
        CustSubscriptionId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The DMS event notification subscription Id.
        SnsTopicArn:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The topic ARN of the DMS event notification subscription.
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The status of the DMS event notification subscription.</p> <p>Constraints:</p> <p>Can be one of the following: creating | modifying | deleting | active | no-permission | topic-not-exist</p> <p>The status "no-permission" indicates that DMS no longer has permission to post to the SNS topic. The status "topic-not-exist" indicates that the topic was deleted after the subscription was created.</p>'
        SubscriptionCreationTime:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The time the DMS event notification subscription was created.
        SourceType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p> The type of DMS resource that generates events. </p> <p>Valid values: replication-instance | replication-server | security-group | replication-task</p>'
        SourceIdsList:
          allOf:
          - $ref: '#/components/schemas/SourceIdsList'
          - description: A list of source Ids for the event subscription.
        EventCategoriesList:
          allOf:
          - $ref: '#/components/schemas/EventCategoriesList'
          - description: A lists of event categories.
        Enabled:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: Boolean value that indicates if the event subscription is enabled.
      description: Describes an event notification subscription created by the <code>CreateEventSubscription</code> operation.
    SourceIdsList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    KMSThrottlingFault: {}
    KMSInvalidStateFault: {}
    BooleanOptional:
      type: boolean
    SNSInvalidTopicFault: {}
    ModifyEventSubscriptionResponse:
      type: object
      properties:
        EventSubscription:
          allOf:
          - $ref: '#/components/schemas/EventSubscription'
          - description: The modified event subscription.
      description: <p/>
    ResourceQuotaExceededFault: {}
    SNSNoAuthorizationFault: {}
    ModifyEventSubscriptionMessage:
      type: object
      required:
      - SubscriptionName
      title: ModifyEventSubscriptionMessage
      properties:
        SubscriptionName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the DMS event notification subscription to be modified.
        SnsTopicArn:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' The Amazon Resource Name (ARN) of the Amazon SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it.'
        SourceType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p> The type of DMS resource that generates the events you want to subscribe to. </p> <p>Valid values: replication-instance | replication-task</p>'
        EventCategories:
          allOf:
          - $ref: '#/components/schemas/EventCategoriesList'
          - description: ' A list of event categories for a source type that you want to subscribe to. Use the <code>DescribeEventCategories</code> action to see a list of event categories. '
        Enabled:
          allOf:
          - $ref: '#/components/schemas/BooleanOptional'
          - description: ' A Boolean value; set to <b>true</b> to activate the subscription. '
      description: <p/>
    EventCategoriesList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    KMSAccessDeniedFault: {}
    String:
      type: string
    Boolean:
      type: boolean
    KMSDisabledFault: {}
    KMSNotFoundFault: {}
    ResourceNotFoundFault: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/dms/
x-hasEquivalentPaths: true
