openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Database Migration Service Endpoints #X Amz Target=AmazonDMSv20160101.DescribeFleetAdvisorDatabases API'
  description: <fullname>Database Migration Service</fullname> <p>Database Migration Service (DMS) can migrate your data to and from the most widely used commercial and open-source databases such as Oracle, PostgreSQL, Microsoft SQL Server, Amazon Redshift, MariaDB, Amazon Aurora, MySQL, and SAP Adaptive Server Enterprise (ASE). The service supports homogeneous migrations such as Oracle to Oracle, as well as heterogeneous migrations between different database platforms, such as Oracle to MySQL or SQL Server to PostgreSQL.</p> <p>For more information about DMS, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html">What Is Database Migration Service?</a> in the <i>Database Migration Service User Guide.</i> </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: dms
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/dms-2016-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: https://dms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Database Migration Service multi-region endpoint
- url: http://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
- url: https://dms.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Database Migration Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AmazonDMSv20160101.DescribeFleetAdvisorDatabases'
paths:
  /#X-Amz-Target=AmazonDMSv20160101.DescribeFleetAdvisorDatabases:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeFleetAdvisorDatabases
      description: Returns a list of Fleet Advisor databases in your account.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeFleetAdvisorDatabasesResponse'
        '480':
          description: InvalidResourceStateFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResourceStateFault'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeFleetAdvisorDatabasesRequest'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AmazonDMSv20160101.DescribeFleetAdvisorDatabases
      tags:
      - '#X Amz Target=AmazonDMSv20160101.DescribeFleetAdvisorDatabases'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    DatabaseInstanceSoftwareDetailsResponse:
      type: object
      properties:
        Engine:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The database engine of a database in a Fleet Advisor collector inventory, for example <code>Microsoft SQL Server</code>.
        EngineVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The database engine version of a database in a Fleet Advisor collector inventory, for example <code>2019</code>.
        EngineEdition:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The database engine edition of a database in a Fleet Advisor collector inventory, for example <code>Express</code>.
        ServicePack:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The service pack level of the database.
        SupportLevel:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The support level of the database, for example <code>Mainstream support</code>.
        OsArchitecture:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: The operating system architecture of the database.
        Tooltip:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Information about the database engine software, for example <code>Mainstream support ends on November 14th, 2024</code>.
      description: Describes an inventory database instance for a Fleet Advisor collector.
    Filter:
      type: object
      required:
      - Name
      - Values
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the filter as specified for a <code>Describe*</code> or similar operation.
        Values:
          allOf:
          - $ref: '#/components/schemas/FilterValueList'
          - description: The filter value, which can specify one or more values used to narrow the returned results.
      description: 'Identifies the name and value of a filter object. This filter is used to limit the number and type of DMS objects that are returned for a particular <code>Describe*</code> call or similar operation. Filters are used as an optional parameter for certain API operations. '
    DescribeFleetAdvisorDatabasesResponse:
      type: object
      properties:
        Databases:
          allOf:
          - $ref: '#/components/schemas/DatabaseList'
          - description: Provides descriptions of the Fleet Advisor collector databases, including the database's collector, ID, and name.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'If <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Make the call again using the returned token to retrieve the next page. Keep all other arguments unchanged. '
    ServerShortInfoResponse:
      type: object
      properties:
        ServerId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The ID of a server in a Fleet Advisor collector inventory.
        IpAddress:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP address of a server in a Fleet Advisor collector inventory.
        ServerName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name address of a server in a Fleet Advisor collector inventory.
      description: Describes a server in a Fleet Advisor collector inventory.
    FilterValueList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    InvalidResourceStateFault: {}
    CollectorsList:
      type: array
      items:
        $ref: '#/components/schemas/CollectorShortInfoResponse'
    DatabaseList:
      type: array
      items:
        $ref: '#/components/schemas/DatabaseResponse'
    IntegerOptional:
      type: integer
    String:
      type: string
    DatabaseResponse:
      type: object
      properties:
        DatabaseId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The ID of a database in a Fleet Advisor collector inventory.
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The name of a database in a Fleet Advisor collector inventory. '
        IpAddress:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The IP address of a database in a Fleet Advisor collector inventory. '
        NumberOfSchemas:
          allOf:
          - $ref: '#/components/schemas/LongOptional'
          - description: 'The number of schemas in a Fleet Advisor collector inventory database. '
        Server:
          allOf:
          - $ref: '#/components/schemas/ServerShortInfoResponse'
          - description: 'The server name of a database in a Fleet Advisor collector inventory. '
        SoftwareDetails:
          allOf:
          - $ref: '#/components/schemas/DatabaseInstanceSoftwareDetailsResponse'
          - description: The software details of a database in a Fleet Advisor collector inventory, such as database engine and version.
        Collectors:
          allOf:
          - $ref: '#/components/schemas/CollectorsList'
          - description: A list of collectors associated with the database.
      description: Describes a database in a Fleet Advisor collector inventory.
    CollectorShortInfoResponse:
      type: object
      properties:
        CollectorReferencedId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The reference ID of the Fleet Advisor collector.
        CollectorName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the Fleet Advisor collector.
      description: Briefly describes a Fleet Advisor collector.
    DescribeFleetAdvisorDatabasesRequest:
      type: object
      title: DescribeFleetAdvisorDatabasesRequest
      properties:
        Filters:
          allOf:
          - $ref: '#/components/schemas/FilterList'
          - description: '<p> If you specify any of the following filters, the output includes information for only those databases that meet the filter criteria: </p> <ul> <li> <p> <code>database-id</code> – The ID of the database.</p> </li> <li> <p> <code>database-name</code> – The name of the database.</p> </li> <li> <p> <code>database-engine</code> – The name of the database engine.</p> </li> <li> <p> <code>server-ip-address</code> – The IP address of the database server.</p> </li> <li> <p> <code>database-ip-address</code> – The IP address of the database.</p> </li> <li> <p> <code>collector-name</code> – The name of the associated Fleet Advisor collector.</p> </li> </ul> <p>An example is: <code>describe-fleet-advisor-databases --filter Name="database-id",Values="45"</code> </p>'
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: Sets the maximum number of records returned in the response.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'If <code>NextToken</code> is returned by a previous response, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Make the call again using the returned token to retrieve the next page. Keep all other arguments unchanged. '
    LongOptional:
      type: integer
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/dms/
x-hasEquivalentPaths: true
